### ISSUE TITLE
How to handle repeat chores?

### ISSUE THREAD

**Issue by leggettc18** [leggettc13/ChoreTracker2#2]
How do we want to handle repeating chores? Do we just generate a set amount of them in a row or automatically generate a new chore when the date passes or upon completion? How do we want to handle it?

**Comment by DecafMegalodon** [comment]
I can see two reasonable ways to handle this:
1) We have some kind of handler that we query and ask for a limited number of instances of that chore. Maybe have a start and end date and it'll return a instances, possibly with completion/approval status?
2) Going along with what you were saying, we could generate a new one when we complete or try to view an expired chore.

I personally prefer 1 because 2 fills up the database with lots of repeated tasks and could slow down queries down the line.

Here's how I imagine chore completion tracking:
We still input an entry to the completion table. I can't see any way around this.

**Comment by napolij14** [comment]
If filling the database is an issue (I'm not sure it would be, esp in this scale, if we were being real, we wouldn't use sqlite) but if it is an issue, we just have a function check when the chore gets completed set to true, we check if it needs to be reapeated and do so....BUT kind of destroys some of the user experience imo

**Comment by napolij14** [comment]
If i make a chore to repeat every day, I would want my child to see that they have that coming up or needs to be done. Of course we can have highlight of due today, but looking into the future is convenient to users in my opinion.
